package com.softwinner.protocol.controller;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reported.proto

public final class Reported {
  private Reported() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqReportedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .ReportedInfo reportedInfo = 1;
    /**
     * <code>repeated .ReportedInfo reportedInfo = 1;</code>
     *
     * <pre>
     *多条上报的数据
     * </pre>
     */
    java.util.List<Reported.ReportedInfo> 
        getReportedInfoList();
    /**
     * <code>repeated .ReportedInfo reportedInfo = 1;</code>
     *
     * <pre>
     *多条上报的数据
     * </pre>
     */
    Reported.ReportedInfo getReportedInfo(int index);
    /**
     * <code>repeated .ReportedInfo reportedInfo = 1;</code>
     *
     * <pre>
     *多条上报的数据
     * </pre>
     */
    int getReportedInfoCount();
    /**
     * <code>repeated .ReportedInfo reportedInfo = 1;</code>
     *
     * <pre>
     *多条上报的数据
     * </pre>
     */
    java.util.List<? extends Reported.ReportedInfoOrBuilder> 
        getReportedInfoOrBuilderList();
    /**
     * <code>repeated .ReportedInfo reportedInfo = 1;</code>
     *
     * <pre>
     *多条上报的数据
     * </pre>
     */
    Reported.ReportedInfoOrBuilder getReportedInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ReqReported}
   *
   * <pre>
   *============================================ 统一数据上报接口
   * </pre>
   */
  public static final class ReqReported extends
      com.google.protobuf.GeneratedMessage
      implements ReqReportedOrBuilder {
    // Use ReqReported.newBuilder() to construct.
    private ReqReported(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqReported(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqReported defaultInstance;
    public static ReqReported getDefaultInstance() {
      return defaultInstance;
    }

    public ReqReported getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqReported(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                reportedInfo_ = new java.util.ArrayList<Reported.ReportedInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              reportedInfo_.add(input.readMessage(Reported.ReportedInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          reportedInfo_ = java.util.Collections.unmodifiableList(reportedInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Reported.internal_static_ReqReported_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Reported.internal_static_ReqReported_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Reported.ReqReported.class, Reported.ReqReported.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqReported> PARSER =
        new com.google.protobuf.AbstractParser<ReqReported>() {
      public ReqReported parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqReported(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqReported> getParserForType() {
      return PARSER;
    }

    // repeated .ReportedInfo reportedInfo = 1;
    public static final int REPORTEDINFO_FIELD_NUMBER = 1;
    private java.util.List<Reported.ReportedInfo> reportedInfo_;
    /**
     * <code>repeated .ReportedInfo reportedInfo = 1;</code>
     *
     * <pre>
     *多条上报的数据
     * </pre>
     */
    public java.util.List<Reported.ReportedInfo> getReportedInfoList() {
      return reportedInfo_;
    }
    /**
     * <code>repeated .ReportedInfo reportedInfo = 1;</code>
     *
     * <pre>
     *多条上报的数据
     * </pre>
     */
    public java.util.List<? extends Reported.ReportedInfoOrBuilder> 
        getReportedInfoOrBuilderList() {
      return reportedInfo_;
    }
    /**
     * <code>repeated .ReportedInfo reportedInfo = 1;</code>
     *
     * <pre>
     *多条上报的数据
     * </pre>
     */
    public int getReportedInfoCount() {
      return reportedInfo_.size();
    }
    /**
     * <code>repeated .ReportedInfo reportedInfo = 1;</code>
     *
     * <pre>
     *多条上报的数据
     * </pre>
     */
    public Reported.ReportedInfo getReportedInfo(int index) {
      return reportedInfo_.get(index);
    }
    /**
     * <code>repeated .ReportedInfo reportedInfo = 1;</code>
     *
     * <pre>
     *多条上报的数据
     * </pre>
     */
    public Reported.ReportedInfoOrBuilder getReportedInfoOrBuilder(
        int index) {
      return reportedInfo_.get(index);
    }

    private void initFields() {
      reportedInfo_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getReportedInfoCount(); i++) {
        if (!getReportedInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < reportedInfo_.size(); i++) {
        output.writeMessage(1, reportedInfo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < reportedInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, reportedInfo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Reported.ReqReported parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Reported.ReqReported parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Reported.ReqReported parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Reported.ReqReported parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Reported.ReqReported parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Reported.ReqReported parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Reported.ReqReported parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Reported.ReqReported parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Reported.ReqReported parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Reported.ReqReported parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Reported.ReqReported prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReqReported}
     *
     * <pre>
     *============================================ 统一数据上报接口
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Reported.ReqReportedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Reported.internal_static_ReqReported_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Reported.internal_static_ReqReported_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Reported.ReqReported.class, Reported.ReqReported.Builder.class);
      }

      // Construct using Reported.ReqReported.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getReportedInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (reportedInfoBuilder_ == null) {
          reportedInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          reportedInfoBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Reported.internal_static_ReqReported_descriptor;
      }

      public Reported.ReqReported getDefaultInstanceForType() {
        return Reported.ReqReported.getDefaultInstance();
      }

      public Reported.ReqReported build() {
        Reported.ReqReported result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Reported.ReqReported buildPartial() {
        Reported.ReqReported result = new Reported.ReqReported(this);
        int from_bitField0_ = bitField0_;
        if (reportedInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            reportedInfo_ = java.util.Collections.unmodifiableList(reportedInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.reportedInfo_ = reportedInfo_;
        } else {
          result.reportedInfo_ = reportedInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Reported.ReqReported) {
          return mergeFrom((Reported.ReqReported)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Reported.ReqReported other) {
        if (other == Reported.ReqReported.getDefaultInstance()) return this;
        if (reportedInfoBuilder_ == null) {
          if (!other.reportedInfo_.isEmpty()) {
            if (reportedInfo_.isEmpty()) {
              reportedInfo_ = other.reportedInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureReportedInfoIsMutable();
              reportedInfo_.addAll(other.reportedInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.reportedInfo_.isEmpty()) {
            if (reportedInfoBuilder_.isEmpty()) {
              reportedInfoBuilder_.dispose();
              reportedInfoBuilder_ = null;
              reportedInfo_ = other.reportedInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              reportedInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getReportedInfoFieldBuilder() : null;
            } else {
              reportedInfoBuilder_.addAllMessages(other.reportedInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getReportedInfoCount(); i++) {
          if (!getReportedInfo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Reported.ReqReported parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Reported.ReqReported) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .ReportedInfo reportedInfo = 1;
      private java.util.List<Reported.ReportedInfo> reportedInfo_ =
        java.util.Collections.emptyList();
      private void ensureReportedInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          reportedInfo_ = new java.util.ArrayList<Reported.ReportedInfo>(reportedInfo_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Reported.ReportedInfo, Reported.ReportedInfo.Builder, Reported.ReportedInfoOrBuilder> reportedInfoBuilder_;

      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public java.util.List<Reported.ReportedInfo> getReportedInfoList() {
        if (reportedInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(reportedInfo_);
        } else {
          return reportedInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public int getReportedInfoCount() {
        if (reportedInfoBuilder_ == null) {
          return reportedInfo_.size();
        } else {
          return reportedInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public Reported.ReportedInfo getReportedInfo(int index) {
        if (reportedInfoBuilder_ == null) {
          return reportedInfo_.get(index);
        } else {
          return reportedInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public Builder setReportedInfo(
          int index, Reported.ReportedInfo value) {
        if (reportedInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReportedInfoIsMutable();
          reportedInfo_.set(index, value);
          onChanged();
        } else {
          reportedInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public Builder setReportedInfo(
          int index, Reported.ReportedInfo.Builder builderForValue) {
        if (reportedInfoBuilder_ == null) {
          ensureReportedInfoIsMutable();
          reportedInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          reportedInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public Builder addReportedInfo(Reported.ReportedInfo value) {
        if (reportedInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReportedInfoIsMutable();
          reportedInfo_.add(value);
          onChanged();
        } else {
          reportedInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public Builder addReportedInfo(
          int index, Reported.ReportedInfo value) {
        if (reportedInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReportedInfoIsMutable();
          reportedInfo_.add(index, value);
          onChanged();
        } else {
          reportedInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public Builder addReportedInfo(
          Reported.ReportedInfo.Builder builderForValue) {
        if (reportedInfoBuilder_ == null) {
          ensureReportedInfoIsMutable();
          reportedInfo_.add(builderForValue.build());
          onChanged();
        } else {
          reportedInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public Builder addReportedInfo(
          int index, Reported.ReportedInfo.Builder builderForValue) {
        if (reportedInfoBuilder_ == null) {
          ensureReportedInfoIsMutable();
          reportedInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          reportedInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public Builder addAllReportedInfo(
          java.lang.Iterable<? extends Reported.ReportedInfo> values) {
        if (reportedInfoBuilder_ == null) {
          ensureReportedInfoIsMutable();
          super.addAll(values, reportedInfo_);
          onChanged();
        } else {
          reportedInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public Builder clearReportedInfo() {
        if (reportedInfoBuilder_ == null) {
          reportedInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          reportedInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public Builder removeReportedInfo(int index) {
        if (reportedInfoBuilder_ == null) {
          ensureReportedInfoIsMutable();
          reportedInfo_.remove(index);
          onChanged();
        } else {
          reportedInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public Reported.ReportedInfo.Builder getReportedInfoBuilder(
          int index) {
        return getReportedInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public Reported.ReportedInfoOrBuilder getReportedInfoOrBuilder(
          int index) {
        if (reportedInfoBuilder_ == null) {
          return reportedInfo_.get(index);  } else {
          return reportedInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public java.util.List<? extends Reported.ReportedInfoOrBuilder> 
           getReportedInfoOrBuilderList() {
        if (reportedInfoBuilder_ != null) {
          return reportedInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(reportedInfo_);
        }
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public Reported.ReportedInfo.Builder addReportedInfoBuilder() {
        return getReportedInfoFieldBuilder().addBuilder(
            Reported.ReportedInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public Reported.ReportedInfo.Builder addReportedInfoBuilder(
          int index) {
        return getReportedInfoFieldBuilder().addBuilder(
            index, Reported.ReportedInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .ReportedInfo reportedInfo = 1;</code>
       *
       * <pre>
       *多条上报的数据
       * </pre>
       */
      public java.util.List<Reported.ReportedInfo.Builder> 
           getReportedInfoBuilderList() {
        return getReportedInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Reported.ReportedInfo, Reported.ReportedInfo.Builder, Reported.ReportedInfoOrBuilder> 
          getReportedInfoFieldBuilder() {
        if (reportedInfoBuilder_ == null) {
          reportedInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Reported.ReportedInfo, Reported.ReportedInfo.Builder, Reported.ReportedInfoOrBuilder>(
                  reportedInfo_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          reportedInfo_ = null;
        }
        return reportedInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ReqReported)
    }

    static {
      defaultInstance = new ReqReported(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ReqReported)
  }

  public interface ReportedInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 statActId = 1;
    /**
     * <code>required int32 statActId = 1;</code>
     *
     * <pre>
     * 统计操作id1 
     * </pre>
     */
    boolean hasStatActId();
    /**
     * <code>required int32 statActId = 1;</code>
     *
     * <pre>
     * 统计操作id1 
     * </pre>
     */
    int getStatActId();

    // optional int32 statActId2 = 2;
    /**
     * <code>optional int32 statActId2 = 2;</code>
     *
     * <pre>
     * 统计操作id2
     * </pre>
     */
    boolean hasStatActId2();
    /**
     * <code>optional int32 statActId2 = 2;</code>
     *
     * <pre>
     * 统计操作id2
     * </pre>
     */
    int getStatActId2();

    // optional string actionTime = 3;
    /**
     * <code>optional string actionTime = 3;</code>
     *
     * <pre>
     * 操作时间 yyyyMMddHHmmss  
     * </pre>
     */
    boolean hasActionTime();
    /**
     * <code>optional string actionTime = 3;</code>
     *
     * <pre>
     * 操作时间 yyyyMMddHHmmss  
     * </pre>
     */
    java.lang.String getActionTime();
    /**
     * <code>optional string actionTime = 3;</code>
     *
     * <pre>
     * 操作时间 yyyyMMddHHmmss  
     * </pre>
     */
    com.google.protobuf.ByteString
        getActionTimeBytes();

    // optional string ext1 = 4;
    /**
     * <code>optional string ext1 = 4;</code>
     *
     * <pre>
     * 扩展字段1-5，用于额外补充的需要上报的数据。
     * </pre>
     */
    boolean hasExt1();
    /**
     * <code>optional string ext1 = 4;</code>
     *
     * <pre>
     * 扩展字段1-5，用于额外补充的需要上报的数据。
     * </pre>
     */
    java.lang.String getExt1();
    /**
     * <code>optional string ext1 = 4;</code>
     *
     * <pre>
     * 扩展字段1-5，用于额外补充的需要上报的数据。
     * </pre>
     */
    com.google.protobuf.ByteString
        getExt1Bytes();

    // optional string ext2 = 5;
    /**
     * <code>optional string ext2 = 5;</code>
     */
    boolean hasExt2();
    /**
     * <code>optional string ext2 = 5;</code>
     */
    java.lang.String getExt2();
    /**
     * <code>optional string ext2 = 5;</code>
     */
    com.google.protobuf.ByteString
        getExt2Bytes();

    // optional string ext3 = 6;
    /**
     * <code>optional string ext3 = 6;</code>
     */
    boolean hasExt3();
    /**
     * <code>optional string ext3 = 6;</code>
     */
    java.lang.String getExt3();
    /**
     * <code>optional string ext3 = 6;</code>
     */
    com.google.protobuf.ByteString
        getExt3Bytes();

    // optional string ext4 = 7;
    /**
     * <code>optional string ext4 = 7;</code>
     */
    boolean hasExt4();
    /**
     * <code>optional string ext4 = 7;</code>
     */
    java.lang.String getExt4();
    /**
     * <code>optional string ext4 = 7;</code>
     */
    com.google.protobuf.ByteString
        getExt4Bytes();

    // optional string ext5 = 8;
    /**
     * <code>optional string ext5 = 8;</code>
     */
    boolean hasExt5();
    /**
     * <code>optional string ext5 = 8;</code>
     */
    java.lang.String getExt5();
    /**
     * <code>optional string ext5 = 8;</code>
     */
    com.google.protobuf.ByteString
        getExt5Bytes();
  }
  /**
   * Protobuf type {@code ReportedInfo}
   */
  public static final class ReportedInfo extends
      com.google.protobuf.GeneratedMessage
      implements ReportedInfoOrBuilder {
    // Use ReportedInfo.newBuilder() to construct.
    private ReportedInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReportedInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReportedInfo defaultInstance;
    public static ReportedInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ReportedInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReportedInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              statActId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              statActId2_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              actionTime_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              ext1_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              ext2_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              ext3_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              ext4_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              ext5_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Reported.internal_static_ReportedInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Reported.internal_static_ReportedInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Reported.ReportedInfo.class, Reported.ReportedInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ReportedInfo> PARSER =
        new com.google.protobuf.AbstractParser<ReportedInfo>() {
      public ReportedInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReportedInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReportedInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 statActId = 1;
    public static final int STATACTID_FIELD_NUMBER = 1;
    private int statActId_;
    /**
     * <code>required int32 statActId = 1;</code>
     *
     * <pre>
     * 统计操作id1 
     * </pre>
     */
    public boolean hasStatActId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 statActId = 1;</code>
     *
     * <pre>
     * 统计操作id1 
     * </pre>
     */
    public int getStatActId() {
      return statActId_;
    }

    // optional int32 statActId2 = 2;
    public static final int STATACTID2_FIELD_NUMBER = 2;
    private int statActId2_;
    /**
     * <code>optional int32 statActId2 = 2;</code>
     *
     * <pre>
     * 统计操作id2
     * </pre>
     */
    public boolean hasStatActId2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 statActId2 = 2;</code>
     *
     * <pre>
     * 统计操作id2
     * </pre>
     */
    public int getStatActId2() {
      return statActId2_;
    }

    // optional string actionTime = 3;
    public static final int ACTIONTIME_FIELD_NUMBER = 3;
    private java.lang.Object actionTime_;
    /**
     * <code>optional string actionTime = 3;</code>
     *
     * <pre>
     * 操作时间 yyyyMMddHHmmss  
     * </pre>
     */
    public boolean hasActionTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string actionTime = 3;</code>
     *
     * <pre>
     * 操作时间 yyyyMMddHHmmss  
     * </pre>
     */
    public java.lang.String getActionTime() {
      java.lang.Object ref = actionTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          actionTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string actionTime = 3;</code>
     *
     * <pre>
     * 操作时间 yyyyMMddHHmmss  
     * </pre>
     */
    public com.google.protobuf.ByteString
        getActionTimeBytes() {
      java.lang.Object ref = actionTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actionTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string ext1 = 4;
    public static final int EXT1_FIELD_NUMBER = 4;
    private java.lang.Object ext1_;
    /**
     * <code>optional string ext1 = 4;</code>
     *
     * <pre>
     * 扩展字段1-5，用于额外补充的需要上报的数据。
     * </pre>
     */
    public boolean hasExt1() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string ext1 = 4;</code>
     *
     * <pre>
     * 扩展字段1-5，用于额外补充的需要上报的数据。
     * </pre>
     */
    public java.lang.String getExt1() {
      java.lang.Object ref = ext1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ext1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ext1 = 4;</code>
     *
     * <pre>
     * 扩展字段1-5，用于额外补充的需要上报的数据。
     * </pre>
     */
    public com.google.protobuf.ByteString
        getExt1Bytes() {
      java.lang.Object ref = ext1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ext1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string ext2 = 5;
    public static final int EXT2_FIELD_NUMBER = 5;
    private java.lang.Object ext2_;
    /**
     * <code>optional string ext2 = 5;</code>
     */
    public boolean hasExt2() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string ext2 = 5;</code>
     */
    public java.lang.String getExt2() {
      java.lang.Object ref = ext2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ext2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ext2 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getExt2Bytes() {
      java.lang.Object ref = ext2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ext2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string ext3 = 6;
    public static final int EXT3_FIELD_NUMBER = 6;
    private java.lang.Object ext3_;
    /**
     * <code>optional string ext3 = 6;</code>
     */
    public boolean hasExt3() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string ext3 = 6;</code>
     */
    public java.lang.String getExt3() {
      java.lang.Object ref = ext3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ext3_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ext3 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getExt3Bytes() {
      java.lang.Object ref = ext3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ext3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string ext4 = 7;
    public static final int EXT4_FIELD_NUMBER = 7;
    private java.lang.Object ext4_;
    /**
     * <code>optional string ext4 = 7;</code>
     */
    public boolean hasExt4() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string ext4 = 7;</code>
     */
    public java.lang.String getExt4() {
      java.lang.Object ref = ext4_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ext4_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ext4 = 7;</code>
     */
    public com.google.protobuf.ByteString
        getExt4Bytes() {
      java.lang.Object ref = ext4_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ext4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string ext5 = 8;
    public static final int EXT5_FIELD_NUMBER = 8;
    private java.lang.Object ext5_;
    /**
     * <code>optional string ext5 = 8;</code>
     */
    public boolean hasExt5() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string ext5 = 8;</code>
     */
    public java.lang.String getExt5() {
      java.lang.Object ref = ext5_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ext5_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ext5 = 8;</code>
     */
    public com.google.protobuf.ByteString
        getExt5Bytes() {
      java.lang.Object ref = ext5_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ext5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      statActId_ = 0;
      statActId2_ = 0;
      actionTime_ = "";
      ext1_ = "";
      ext2_ = "";
      ext3_ = "";
      ext4_ = "";
      ext5_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStatActId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, statActId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, statActId2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getActionTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getExt1Bytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getExt2Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getExt3Bytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getExt4Bytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getExt5Bytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, statActId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, statActId2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getActionTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getExt1Bytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getExt2Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getExt3Bytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getExt4Bytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getExt5Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Reported.ReportedInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Reported.ReportedInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Reported.ReportedInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Reported.ReportedInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Reported.ReportedInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Reported.ReportedInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Reported.ReportedInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Reported.ReportedInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Reported.ReportedInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Reported.ReportedInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Reported.ReportedInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReportedInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Reported.ReportedInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Reported.internal_static_ReportedInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Reported.internal_static_ReportedInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Reported.ReportedInfo.class, Reported.ReportedInfo.Builder.class);
      }

      // Construct using Reported.ReportedInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        statActId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        statActId2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        actionTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        ext1_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        ext2_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        ext3_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        ext4_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        ext5_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Reported.internal_static_ReportedInfo_descriptor;
      }

      public Reported.ReportedInfo getDefaultInstanceForType() {
        return Reported.ReportedInfo.getDefaultInstance();
      }

      public Reported.ReportedInfo build() {
        Reported.ReportedInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Reported.ReportedInfo buildPartial() {
        Reported.ReportedInfo result = new Reported.ReportedInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.statActId_ = statActId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.statActId2_ = statActId2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.actionTime_ = actionTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ext1_ = ext1_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ext2_ = ext2_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ext3_ = ext3_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.ext4_ = ext4_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.ext5_ = ext5_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Reported.ReportedInfo) {
          return mergeFrom((Reported.ReportedInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Reported.ReportedInfo other) {
        if (other == Reported.ReportedInfo.getDefaultInstance()) return this;
        if (other.hasStatActId()) {
          setStatActId(other.getStatActId());
        }
        if (other.hasStatActId2()) {
          setStatActId2(other.getStatActId2());
        }
        if (other.hasActionTime()) {
          bitField0_ |= 0x00000004;
          actionTime_ = other.actionTime_;
          onChanged();
        }
        if (other.hasExt1()) {
          bitField0_ |= 0x00000008;
          ext1_ = other.ext1_;
          onChanged();
        }
        if (other.hasExt2()) {
          bitField0_ |= 0x00000010;
          ext2_ = other.ext2_;
          onChanged();
        }
        if (other.hasExt3()) {
          bitField0_ |= 0x00000020;
          ext3_ = other.ext3_;
          onChanged();
        }
        if (other.hasExt4()) {
          bitField0_ |= 0x00000040;
          ext4_ = other.ext4_;
          onChanged();
        }
        if (other.hasExt5()) {
          bitField0_ |= 0x00000080;
          ext5_ = other.ext5_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatActId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Reported.ReportedInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Reported.ReportedInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 statActId = 1;
      private int statActId_ ;
      /**
       * <code>required int32 statActId = 1;</code>
       *
       * <pre>
       * 统计操作id1 
       * </pre>
       */
      public boolean hasStatActId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 statActId = 1;</code>
       *
       * <pre>
       * 统计操作id1 
       * </pre>
       */
      public int getStatActId() {
        return statActId_;
      }
      /**
       * <code>required int32 statActId = 1;</code>
       *
       * <pre>
       * 统计操作id1 
       * </pre>
       */
      public Builder setStatActId(int value) {
        bitField0_ |= 0x00000001;
        statActId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 statActId = 1;</code>
       *
       * <pre>
       * 统计操作id1 
       * </pre>
       */
      public Builder clearStatActId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        statActId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 statActId2 = 2;
      private int statActId2_ ;
      /**
       * <code>optional int32 statActId2 = 2;</code>
       *
       * <pre>
       * 统计操作id2
       * </pre>
       */
      public boolean hasStatActId2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 statActId2 = 2;</code>
       *
       * <pre>
       * 统计操作id2
       * </pre>
       */
      public int getStatActId2() {
        return statActId2_;
      }
      /**
       * <code>optional int32 statActId2 = 2;</code>
       *
       * <pre>
       * 统计操作id2
       * </pre>
       */
      public Builder setStatActId2(int value) {
        bitField0_ |= 0x00000002;
        statActId2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 statActId2 = 2;</code>
       *
       * <pre>
       * 统计操作id2
       * </pre>
       */
      public Builder clearStatActId2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        statActId2_ = 0;
        onChanged();
        return this;
      }

      // optional string actionTime = 3;
      private java.lang.Object actionTime_ = "";
      /**
       * <code>optional string actionTime = 3;</code>
       *
       * <pre>
       * 操作时间 yyyyMMddHHmmss  
       * </pre>
       */
      public boolean hasActionTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string actionTime = 3;</code>
       *
       * <pre>
       * 操作时间 yyyyMMddHHmmss  
       * </pre>
       */
      public java.lang.String getActionTime() {
        java.lang.Object ref = actionTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          actionTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string actionTime = 3;</code>
       *
       * <pre>
       * 操作时间 yyyyMMddHHmmss  
       * </pre>
       */
      public com.google.protobuf.ByteString
          getActionTimeBytes() {
        java.lang.Object ref = actionTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          actionTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string actionTime = 3;</code>
       *
       * <pre>
       * 操作时间 yyyyMMddHHmmss  
       * </pre>
       */
      public Builder setActionTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        actionTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string actionTime = 3;</code>
       *
       * <pre>
       * 操作时间 yyyyMMddHHmmss  
       * </pre>
       */
      public Builder clearActionTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        actionTime_ = getDefaultInstance().getActionTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string actionTime = 3;</code>
       *
       * <pre>
       * 操作时间 yyyyMMddHHmmss  
       * </pre>
       */
      public Builder setActionTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        actionTime_ = value;
        onChanged();
        return this;
      }

      // optional string ext1 = 4;
      private java.lang.Object ext1_ = "";
      /**
       * <code>optional string ext1 = 4;</code>
       *
       * <pre>
       * 扩展字段1-5，用于额外补充的需要上报的数据。
       * </pre>
       */
      public boolean hasExt1() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string ext1 = 4;</code>
       *
       * <pre>
       * 扩展字段1-5，用于额外补充的需要上报的数据。
       * </pre>
       */
      public java.lang.String getExt1() {
        java.lang.Object ref = ext1_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ext1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ext1 = 4;</code>
       *
       * <pre>
       * 扩展字段1-5，用于额外补充的需要上报的数据。
       * </pre>
       */
      public com.google.protobuf.ByteString
          getExt1Bytes() {
        java.lang.Object ref = ext1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ext1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ext1 = 4;</code>
       *
       * <pre>
       * 扩展字段1-5，用于额外补充的需要上报的数据。
       * </pre>
       */
      public Builder setExt1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ext1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ext1 = 4;</code>
       *
       * <pre>
       * 扩展字段1-5，用于额外补充的需要上报的数据。
       * </pre>
       */
      public Builder clearExt1() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ext1_ = getDefaultInstance().getExt1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ext1 = 4;</code>
       *
       * <pre>
       * 扩展字段1-5，用于额外补充的需要上报的数据。
       * </pre>
       */
      public Builder setExt1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ext1_ = value;
        onChanged();
        return this;
      }

      // optional string ext2 = 5;
      private java.lang.Object ext2_ = "";
      /**
       * <code>optional string ext2 = 5;</code>
       */
      public boolean hasExt2() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string ext2 = 5;</code>
       */
      public java.lang.String getExt2() {
        java.lang.Object ref = ext2_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ext2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ext2 = 5;</code>
       */
      public com.google.protobuf.ByteString
          getExt2Bytes() {
        java.lang.Object ref = ext2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ext2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ext2 = 5;</code>
       */
      public Builder setExt2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        ext2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ext2 = 5;</code>
       */
      public Builder clearExt2() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ext2_ = getDefaultInstance().getExt2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ext2 = 5;</code>
       */
      public Builder setExt2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        ext2_ = value;
        onChanged();
        return this;
      }

      // optional string ext3 = 6;
      private java.lang.Object ext3_ = "";
      /**
       * <code>optional string ext3 = 6;</code>
       */
      public boolean hasExt3() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string ext3 = 6;</code>
       */
      public java.lang.String getExt3() {
        java.lang.Object ref = ext3_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ext3_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ext3 = 6;</code>
       */
      public com.google.protobuf.ByteString
          getExt3Bytes() {
        java.lang.Object ref = ext3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ext3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ext3 = 6;</code>
       */
      public Builder setExt3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ext3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ext3 = 6;</code>
       */
      public Builder clearExt3() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ext3_ = getDefaultInstance().getExt3();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ext3 = 6;</code>
       */
      public Builder setExt3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ext3_ = value;
        onChanged();
        return this;
      }

      // optional string ext4 = 7;
      private java.lang.Object ext4_ = "";
      /**
       * <code>optional string ext4 = 7;</code>
       */
      public boolean hasExt4() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string ext4 = 7;</code>
       */
      public java.lang.String getExt4() {
        java.lang.Object ref = ext4_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ext4_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ext4 = 7;</code>
       */
      public com.google.protobuf.ByteString
          getExt4Bytes() {
        java.lang.Object ref = ext4_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ext4_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ext4 = 7;</code>
       */
      public Builder setExt4(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        ext4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ext4 = 7;</code>
       */
      public Builder clearExt4() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ext4_ = getDefaultInstance().getExt4();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ext4 = 7;</code>
       */
      public Builder setExt4Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        ext4_ = value;
        onChanged();
        return this;
      }

      // optional string ext5 = 8;
      private java.lang.Object ext5_ = "";
      /**
       * <code>optional string ext5 = 8;</code>
       */
      public boolean hasExt5() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string ext5 = 8;</code>
       */
      public java.lang.String getExt5() {
        java.lang.Object ref = ext5_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ext5_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ext5 = 8;</code>
       */
      public com.google.protobuf.ByteString
          getExt5Bytes() {
        java.lang.Object ref = ext5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ext5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ext5 = 8;</code>
       */
      public Builder setExt5(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        ext5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ext5 = 8;</code>
       */
      public Builder clearExt5() {
        bitField0_ = (bitField0_ & ~0x00000080);
        ext5_ = getDefaultInstance().getExt5();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ext5 = 8;</code>
       */
      public Builder setExt5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        ext5_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReportedInfo)
    }

    static {
      defaultInstance = new ReportedInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ReportedInfo)
  }

  public interface RspReportedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 rescode = 1;
    /**
     * <code>required int32 rescode = 1;</code>
     *
     * <pre>
     * 返回码：0=成功，1=失败
     * </pre>
     */
    boolean hasRescode();
    /**
     * <code>required int32 rescode = 1;</code>
     *
     * <pre>
     * 返回码：0=成功，1=失败
     * </pre>
     */
    int getRescode();

    // required string resmsg = 2;
    /**
     * <code>required string resmsg = 2;</code>
     *
     * <pre>
     * 返回消息
     * </pre>
     */
    boolean hasResmsg();
    /**
     * <code>required string resmsg = 2;</code>
     *
     * <pre>
     * 返回消息
     * </pre>
     */
    java.lang.String getResmsg();
    /**
     * <code>required string resmsg = 2;</code>
     *
     * <pre>
     * 返回消息
     * </pre>
     */
    com.google.protobuf.ByteString
        getResmsgBytes();
  }
  /**
   * Protobuf type {@code RspReported}
   */
  public static final class RspReported extends
      com.google.protobuf.GeneratedMessage
      implements RspReportedOrBuilder {
    // Use RspReported.newBuilder() to construct.
    private RspReported(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RspReported(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RspReported defaultInstance;
    public static RspReported getDefaultInstance() {
      return defaultInstance;
    }

    public RspReported getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RspReported(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rescode_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              resmsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Reported.internal_static_RspReported_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Reported.internal_static_RspReported_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Reported.RspReported.class, Reported.RspReported.Builder.class);
    }

    public static com.google.protobuf.Parser<RspReported> PARSER =
        new com.google.protobuf.AbstractParser<RspReported>() {
      public RspReported parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RspReported(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RspReported> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 rescode = 1;
    public static final int RESCODE_FIELD_NUMBER = 1;
    private int rescode_;
    /**
     * <code>required int32 rescode = 1;</code>
     *
     * <pre>
     * 返回码：0=成功，1=失败
     * </pre>
     */
    public boolean hasRescode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 rescode = 1;</code>
     *
     * <pre>
     * 返回码：0=成功，1=失败
     * </pre>
     */
    public int getRescode() {
      return rescode_;
    }

    // required string resmsg = 2;
    public static final int RESMSG_FIELD_NUMBER = 2;
    private java.lang.Object resmsg_;
    /**
     * <code>required string resmsg = 2;</code>
     *
     * <pre>
     * 返回消息
     * </pre>
     */
    public boolean hasResmsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string resmsg = 2;</code>
     *
     * <pre>
     * 返回消息
     * </pre>
     */
    public java.lang.String getResmsg() {
      java.lang.Object ref = resmsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resmsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string resmsg = 2;</code>
     *
     * <pre>
     * 返回消息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getResmsgBytes() {
      java.lang.Object ref = resmsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resmsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      rescode_ = 0;
      resmsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRescode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResmsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rescode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getResmsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rescode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getResmsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Reported.RspReported parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Reported.RspReported parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Reported.RspReported parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Reported.RspReported parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Reported.RspReported parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Reported.RspReported parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Reported.RspReported parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Reported.RspReported parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Reported.RspReported parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Reported.RspReported parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Reported.RspReported prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RspReported}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Reported.RspReportedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Reported.internal_static_RspReported_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Reported.internal_static_RspReported_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Reported.RspReported.class, Reported.RspReported.Builder.class);
      }

      // Construct using Reported.RspReported.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rescode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        resmsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Reported.internal_static_RspReported_descriptor;
      }

      public Reported.RspReported getDefaultInstanceForType() {
        return Reported.RspReported.getDefaultInstance();
      }

      public Reported.RspReported build() {
        Reported.RspReported result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Reported.RspReported buildPartial() {
        Reported.RspReported result = new Reported.RspReported(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rescode_ = rescode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resmsg_ = resmsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Reported.RspReported) {
          return mergeFrom((Reported.RspReported)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Reported.RspReported other) {
        if (other == Reported.RspReported.getDefaultInstance()) return this;
        if (other.hasRescode()) {
          setRescode(other.getRescode());
        }
        if (other.hasResmsg()) {
          bitField0_ |= 0x00000002;
          resmsg_ = other.resmsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRescode()) {
          
          return false;
        }
        if (!hasResmsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Reported.RspReported parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Reported.RspReported) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 rescode = 1;
      private int rescode_ ;
      /**
       * <code>required int32 rescode = 1;</code>
       *
       * <pre>
       * 返回码：0=成功，1=失败
       * </pre>
       */
      public boolean hasRescode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 rescode = 1;</code>
       *
       * <pre>
       * 返回码：0=成功，1=失败
       * </pre>
       */
      public int getRescode() {
        return rescode_;
      }
      /**
       * <code>required int32 rescode = 1;</code>
       *
       * <pre>
       * 返回码：0=成功，1=失败
       * </pre>
       */
      public Builder setRescode(int value) {
        bitField0_ |= 0x00000001;
        rescode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rescode = 1;</code>
       *
       * <pre>
       * 返回码：0=成功，1=失败
       * </pre>
       */
      public Builder clearRescode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rescode_ = 0;
        onChanged();
        return this;
      }

      // required string resmsg = 2;
      private java.lang.Object resmsg_ = "";
      /**
       * <code>required string resmsg = 2;</code>
       *
       * <pre>
       * 返回消息
       * </pre>
       */
      public boolean hasResmsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string resmsg = 2;</code>
       *
       * <pre>
       * 返回消息
       * </pre>
       */
      public java.lang.String getResmsg() {
        java.lang.Object ref = resmsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          resmsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string resmsg = 2;</code>
       *
       * <pre>
       * 返回消息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getResmsgBytes() {
        java.lang.Object ref = resmsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resmsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string resmsg = 2;</code>
       *
       * <pre>
       * 返回消息
       * </pre>
       */
      public Builder setResmsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resmsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string resmsg = 2;</code>
       *
       * <pre>
       * 返回消息
       * </pre>
       */
      public Builder clearResmsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resmsg_ = getDefaultInstance().getResmsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string resmsg = 2;</code>
       *
       * <pre>
       * 返回消息
       * </pre>
       */
      public Builder setResmsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resmsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RspReported)
    }

    static {
      defaultInstance = new RspReported(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RspReported)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqReported_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqReported_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ReportedInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReportedInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RspReported_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RspReported_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Reported.proto\"2\n\013ReqReported\022#\n\014repor" +
      "tedInfo\030\001 \003(\0132\r.ReportedInfo\"\217\001\n\014Reporte" +
      "dInfo\022\021\n\tstatActId\030\001 \002(\005\022\022\n\nstatActId2\030\002" +
      " \001(\005\022\022\n\nactionTime\030\003 \001(\t\022\014\n\004ext1\030\004 \001(\t\022\014" +
      "\n\004ext2\030\005 \001(\t\022\014\n\004ext3\030\006 \001(\t\022\014\n\004ext4\030\007 \001(\t" +
      "\022\014\n\004ext5\030\010 \001(\t\".\n\013RspReported\022\017\n\007rescode" +
      "\030\001 \002(\005\022\016\n\006resmsg\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ReqReported_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ReqReported_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ReqReported_descriptor,
              new java.lang.String[] { "ReportedInfo", });
          internal_static_ReportedInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ReportedInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ReportedInfo_descriptor,
              new java.lang.String[] { "StatActId", "StatActId2", "ActionTime", "Ext1", "Ext2", "Ext3", "Ext4", "Ext5", });
          internal_static_RspReported_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_RspReported_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RspReported_descriptor,
              new java.lang.String[] { "Rescode", "Resmsg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
